import { Sequelize } from "sequelize-typescript";
import {
  Address,
  Category,
  City,
  Color,
  Contact,
  Discount,
  Gallery,
  Language,
  LocaleStringResource,
  LocalizedProperty,
  Maker,
  MakerBrand,
  News,
  NewsComment,
  NewsType,
  Order,
  OrderItem,
  Payment,
  Picture,
  Product,
  Province,
  QuantityUnit,
  Role,
  SiteInfo,
  Slider,
  SpecificationAttribute,
  SpecificationAttributeOption,
  Tag,
  TaxCategory,
  Ticket,
  User,
} from "../../models";

export const sequelize = new Sequelize({
  dialect: "sqlite",
  storage: "./app.db",
  logging: false,
  models: [
    User,
    Role,
    Address,
    Province,
    City,
    Category,
    Color,
    Contact,
    Discount,
    Gallery,
    Language,
    LocaleStringResource,
    LocalizedProperty,
    Maker,
    MakerBrand,
    News,
    NewsType,
    NewsComment,
    Order,
    OrderItem,
    Product,
    Payment,
    Picture,
    QuantityUnit,
    SiteInfo,
    Slider,
    SpecificationAttribute,
    SpecificationAttributeOption,
    Tag,
    TaxCategory,
    Ticket
  ],
});
